Traceback (most recent call last):
  File "/Users/lyes/Dropbox/UofT/Teaching/MIE1666_F24/1666env/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/lyes/Dropbox/UofT/Teaching/MIE1666_F24/1666env/lib/python3.10/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/lyes/Dropbox/UofT/Teaching/MIE1666_F24/1666env/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/Users/lyes/anaconda3/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/Users/lyes/Dropbox/UofT/Teaching/MIE1666_F24/1666env/lib/python3.10/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/Users/lyes/Dropbox/UofT/Teaching/MIE1666_F24/1666env/lib/python3.10/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/lyes/Dropbox/UofT/Teaching/MIE1666_F24/1666env/lib/python3.10/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
fig, ax = plt.subplots()
x = Symbol('x')
# piecewise_fun = Piecewise(((x+1)**2, x <= -1), (0, x < 1), ((x-1)**2, x >= 1))
p1 = plot(piecewise_fun, show=False, legend=False, fig=fig, ax=ax)
p1.show()
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[12], line 4[0m
[1;32m      2[0m x [38;5;241m=[39m Symbol([38;5;124m'[39m[38;5;124mx[39m[38;5;124m'[39m)
[1;32m      3[0m [38;5;66;03m# piecewise_fun = Piecewise(((x+1)**2, x <= -1), (0, x < 1), ((x-1)**2, x >= 1))[39;00m
[0;32m----> 4[0m p1 [38;5;241m=[39m plot([43mpiecewise_fun[49m, show[38;5;241m=[39m[38;5;28;01mFalse[39;00m, legend[38;5;241m=[39m[38;5;28;01mFalse[39;00m, fig[38;5;241m=[39mfig, ax[38;5;241m=[39max)
[1;32m      5[0m p1[38;5;241m.[39mshow()

[0;31mNameError[0m: name 'piecewise_fun' is not defined

